[package]

name = "slab"
version = "0.2.0"
license = "MIT"
authors = ["Carl Lerche <me@carllerche.com>"]
description = "Simple slab allocator"
documentation = "http://rust-doc.s3-website-us-east-1.amazonaws.com/slab/master/slab/"
homepage = "https://github.com/carllerche/slab"
repository = "https://github.com/carllerche/slab"
readme = "README.md"
keywords = ["slab", "allocator"]
exclude = [
    ".gitignore",
    ".travis.yml",
    "test/**/*",
]
